FROM python:3.9

WORKDIR /app

COPY . /app

RUN apt-get update && apt-get install -y \
    libasound2-dev \
    && pip install --no-cache-dir -r requirements.txt

CMD ["python", "text_to_speech.py"]

