FROM python:3.9-slim

RUN apt-get update && apt-get install -y \
    libasound2-dev \
    espeak \
    ffmpeg \
    libespeak-ng1 \
    libespeak-ng-dev \
    portaudio19-dev \
    pulseaudio \
    alsa-utils \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .
CMD ["python", "text_to_speech.py"]
