FROM python:3.9-slim

RUN apt-get update && apt-get install -y \
    libasound2-dev \
    ffmpeg \
    portaudio19-dev \
    pulseaudio \
    procps \
    && rm -rf /var/lib/apt/lists/*


RUN pip install --no-cache-dir torch openai-whisper

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Copy the entrypoint script
COPY vtt_entrypoint.sh /vtt_entrypoint.sh
RUN chmod +x /vtt_entrypoint.sh

# Use the entrypoint script
ENTRYPOINT ["/vtt_entrypoint.sh"]
