FROM ai/meta-llama:3.1-8B-Instruct-cuda-12.6

RUN apt-get update && apt-get install -y python3-pip

WORKDIR /app
COPY text_processing.py /app
COPY requirements.txt .

CMD ["python3", "text_processing.py"]
