services:
  voice-to-text:
    build:
      context: .
      dockerfile: Dockerfile.voice-to-text
    volumes:
      - /mnt/d/Learning/Personal-Assistant:/app
      - /mnt/wslg:/mnt/wslg # Share PulseAudio configuration
    environment:
      - PULSE_SERVER=unix:/mnt/wslg/PulseServer
      - NVIDIA_VISIBLE_DEVICES=all
    network_mode: "host" # Use host network to enable audio communication
    #devices:
      #- /dev/snd:/dev/snd
    runtime: nvidia
    #restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost || exit 1"]
      interval: 1m30s
      timeout: 10s
      retries: 3

  # text-processing:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.text-processing
  #   volumes:
  #     - /mnt/d/Learning/Personal-Assistant/models:/app/models
  #   devices:
  #     - /dev/snd:/dev/snd
  #   runtime: nvidia
  #   environment:
  #     - NVIDIA_VISIBLE_DEVICES=all
  #   restart: on-failure
  #   healthcheck:
  #     test: ["CMD-SHELL", "curl -f http://localhost || exit 1"]
  #     interval: 1m30s
  #     timeout: 10s
  #     retries: 3

  # text-to-speech:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.text-to-speech
  #   volumes:
  #     - /mnt/d/Learning/Personal-Assistant/models:/app/models
  #   devices:
  #     - /dev/snd:/dev/snd
  #   runtime: nvidia
  #   environment:
  #     - NVIDIA_VISIBLE_DEVICES=all
  #   restart: on-failure
  #   healthcheck:
  #     test: ["CMD-SHELL", "curl -f http://localhost || exit 1"]
  #     interval: 1m30s
  #     timeout: 10s
  #     retries: 3

